name: 'Setup for all'
description: "Setup shared for all jobs"
runs:
  using: 'composite'
  steps:
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.8
          cache: 'pip' # caching pip dependencies
      - name: Install Dependencies
        shell: bash
        run: |
          pip install -r ${{ github.workspace }}/scripts/crowdin/requirements.txt

      - uses: actions/download-artifact@v4
        with:
          name: session-download
          path: "${{ github.workspace }}/raw_translations"

      - name: Display structure of downloaded files
        shell: bash
        run: ls ${{ github.workspace }}/raw_translations