name: 'Setup for all'
description: "Setup shared for all jobs"
runs:
  using: 'composite'
  steps:
      - name: Checkout Android
        uses: actions/checkout@v4
        with:
          repository: 'oxen-io/session-android'
          path: 'android'
          submodules: recursive
          ref: 'dev'
      - name: Remove existing strings
        shell: bash
        run: |
          rm -rf ${{ github.workspace }}/android/libsession/src/main/res/values*/strings.xml
